# Generated by Django 4.1.7 on 2023-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="longitude",
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_description",
            field=models.CharField(default="default", max_length=200),
        ),
        migrations.AddField(
            model_name="hotel",
            name="price",
            field=models.IntegerField(default=100, max_length=200),
        ),
    ]
