# Generated by Django 4.1.7 on 2023-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_latitude_remove_hotel_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
