# Generated by Django 4.1.7 on 2023-04-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='type',
            field=models.CharField(default='premium', max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
