# Generated by Django 4.1.7 on 2023-04-16 21:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotel_type_alter_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('3.5'), max_digits=2, null=True),
        ),
    ]
