# Generated by Django 4.2 on 2023-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_price", models.IntegerField()),
                ("flight_price", models.IntegerField()),
                ("total_price", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="itinerary",
        ),
    ]
