# Generated by Django 4.2 on 2023-04-23 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payments_delete_itinerary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="flight_price",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="hotel_price",
        ),
    ]
