# Generated by Django 4.1.7 on 2023-04-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airlines',
            field=models.CharField(default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(default='default', upload_to='flight_images/'),
        ),
    ]
