# Generated by Django 4.2 on 2023-04-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0004_remove_reservation_passenger_flight_no_of_seats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="email",
            field=models.EmailField(default="", max_length=255),
        ),
    ]
